apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-deployment-service
spec:
  selector:
    app: spring-boot
  ports:
    - port: 80          # Port inside the cluster
      targetPort: 8080  # Port on the pod
      nodePort: 30080   # Port on the VM (between 30000-32767)
      protocol: TCP
  type: NodePort      # Exposes the service on each node's IP