apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-deployment-service
spec:
  selector:
    app: spring-boot
  type: NodePort  # Default type, internal access only
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
