apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes-deployment-service
spec:
  selector:
    app: spring-boot
  type: ClusterIP  # Default type, internal access only
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
