replicaCount: 2

image:
  repository: fbiankevin/springboot-kubernetes-deployment
  tag: "0.0.2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  targetPort: 8080
  nodePort: 30080

config:
  applicationProperties: |
    spring.profiles.active=dev
    server.port=8080
    logging.level.com.fabiankevin=error
    app.user.name=Sandro

secret:
  springDataSourcePassword: "mysecretpassword"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

probes:
  readiness:
    path: "/actuator/health"
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    path: "/actuator/health"
    initialDelaySeconds: 15
    periodSeconds: 20