apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-boot
  labels:
    app: {{ .Release.Name }}-spring-boot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring-boot
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring-boot
    spec:
      containers:
        - name: spring-boot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: springDataSourcePassword  # Matches earlier Secret
          volumeMounts:
            - name: config-volume
              mountPath: "/app/config"
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: application.properties
                path: application.properties